version: '3.7'
services:
    postgres:
        image: postgres:16.1-bullseye
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=root
        ports: 
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=test@mail.com
            - PGADMIN_DEFAULT_PASSWORD=test
        ports: 
            - "5050:80"

