version: '3.7'
services:
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_USER=copyme
            - POSTGRES_PASSWORD=copyme
            - POSTGRES_DB=copyme
        ports: 
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=copyme@mail.com
            - PGADMIN_DEFAULT_PASSWORD=copyme
        ports: 
            - "5050:80"